# Generated by Django 6.0.4 on 2026-04-25 01:36

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='cover_image_partner',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo / Image partenaire'),
        ),
        migrations.AddField(
            model_name='about',
            name='name_fr_partner',
            field=models.CharField(default='', max_length=255, verbose_name='Nom (FR)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL du site web'),
        ),
    ]
